{% set name = "igraph" %}
{% set version = "0.10.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igraph/igraph/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa5700b58c5f1e1de1f4637ab14df15c6b20e25e51d0f5a260921818e8f02afc
build:
  skip: true  # [win and vc<14]
  skip: true  # [linux and (s390x or ppc64le)]
  number: 0
  script_env:
    - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("igraph", max_pin="x.x") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_win-64  # [win]
    - cmake
    - ninja
    - make  # [not win]
      #- python  # [win]
    - pkg-config  # [not win]
    - llvm-openmp  # [osx]
  host:
    - glpk 4.65
    - libxml2 {{ libxml2 }}
    - suitesparse 7.0.1
    - arpack 3.9.0   # [not win]
    - gmp 6.2.1  # [not win]
    - mpir 3.0.0  # [win]
    - openblas  # [not win]
    - intel-openmp {{ mkl }}  # [win]
    - mkl-devel {{ mkl }}.*  # [win]
    - mkl {{ mkl }}.*  # [win]
  run:
    - glpk
    - libxml2
    - suitesparse
    - arpack  # [not win]
    - gmp  # [not win]
    - mpir  # [win]
    - libopenblas  # [not win]
    - {{ pin_compatible('intel-openmp') }}  # [win]
    - mkl {{ mkl }}.*  # [win]
    - _openmp_mutex  # [linux]

test:
  files:
    - igraph_test.c
  requires:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]

about:
  home: https://igraph.org/c/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - ACKNOWLEDGEMENTS.md
  summary: An open source and free collection of network analysis tool.
  description: |
    igraph is a collection of network analysis tools with the emphasis on efficiency,
    portabiliy and ease of use. igraph is open source and free. igraph can be
    programmed in R, Python and C/C++."
  doc_url: https://igraph.org/r/doc/
  dev_url: https://github.com/igraph/igraph

extra:
  recipe-maintainers:
    - sodre
    - vtraag
