{% set name = "igraph" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  url: https://github.com/igraph/igraph/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 72637335600cf4758fd718009b16d92489b58a2f5dd96d884740d20cd5769649  # [not win]

  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/igraph/igraph/releases/download/{{ version }}/{{ name }}-{{ version }}-msvc.zip  # [win]
  sha256: ff1cdcdf4a258b03eeec2075fd879f6d21b0e05efa66d4cc4374f39e70648d9a  # [win]

build:
  skip: True  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage("igraph", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - vs2017_{{ target_platform  }}  # [win]
    - pkg-config  # [not win]
    - make  # [not win]
    - python  # [win]
    - msinttypes  # [win]
  host:
    - gmp  # [not win]
    - icu  # [not win]
    - libiconv  # [not win]
    - libxml2  # [not win]
    - xz  # [not win]
    - zlib  # [not win]
  run:
    - gmp  # [not win]
    - icu  # [not win]
    - libiconv  # [not win]
    - libxml2  # [not win]
    - xz  # [not win]
    - zlib  # [not win]

test:
  files:
    - igraph_test.c
  requires:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  commands:
    - pkg-config --exists igraph  # [not win]
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: http://igraph.org
  license: GPL2
  license_family: GPL
  license_file: COPYING  # [not win]
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'  # [win]
  summary: 'An open source and free collection of network analysis tool.'
  description: |
    igraph is a collection of network analysis tools with the emphasis on efficiency,
    portabiliy and ease of use. igraph is open source and free. igraph can be
    programmed in R, Python and C/C++."

extra:
  recipe-maintainers:
    - sodre
