travis:
  secure:
    BINSTAR_TOKEN: qNVgr0UAODBnC1toPMzItanToO1n+KalmkIJpkBzMRjUUIZkmaT9c1LygKFdsmYWj1N+sFreWdLhSvXn5Y1LkPfiIXZc6PADIeXHcsYEOGqNFin6TAfyNDSJzdSaMcpZ1uiw6nLw3tvLGdeA7qSOxmF9IVbNoJiGRbQpFBB2iNDX75uwA/tKbm31dgc/Fu2uKDWz9nSyWRVnPyWjDIAdfldAC3wWaNZbRNs3eJpyraK7PhbzSFfKfyyj1+M4iG3fatOGv4WrocBIfuYfTS4t/fhsgfMWwfOPHFD7rF7lsKuBvKtPDtn/9gmBi05w6+kCs6aYHj+9wvMRd9CP7PDVhLy4Qmig+jrbUesd97vDWVy8UKhso6akYHO+tLbwVYLwEHyp56I+X8mWt7prw21ZNCmsHuy5ZbPPSR5xb7D419NEcBy0vuC48Vjugp4bThMIULmo5gD81ZYuvIsexQOl7xtOUdj+YlgHti8MJmktsyYfwS8TrMvhMR4RYDZscWjZQ3xSM83TuLVCODZ5jhDFEkaCz6PPcxdRkHRCL3GJ547oIAeBcA0inxhJGl+QZdeAqtnY5nefyWmf39qYllRTms/8n1OXTHH6cXf61FAJPrAGIy0jmBA3jR8X9A+ijqRH1V402yC8p2Y19Wnr23xFZ2zZqRxLr99V8tqHlSIpoTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
