appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Iedv1U50gGse19zBQ/A7L5ZlFoPS8iWisI2nLfH0V0zypn2IWvPyJX3W36NB2PVtK8ve33+/ZkQzlYC+sRUNkMcKY7Bx13tPLpUpQSlbITpvPr5BIGGYAmfM7ADATg1+Qo9s7nLwXkly0QbPX9LgrAbBNGHAUavgTA6kCpD/UF7k4uycRKWjExgsc0D7QdTncYHI3NRMxkHscXAIM2OewGU/TH0YmB7m0EgRRJyIvjxnBdXx45lQAVfCxKgOHH/Jn/dvtMjmqP71ofqHeXgZzJECptnKDGY4nremQBFRnFB0XrgqhvOBJLicoHIsmiHXGe2j/IkgaJwft1nZoz5Y8Vc5uvpT4bxQCkr63IYGey8CINLy0N5CObo2fJJjtiriarrLPeZVDumy5BDRJ5mZwhYw30FP2b7ieSkvuklFNmhVkEGrdWvzLykAi/fF7KeU5xkNxoNdt2LSo0FxGT/jzlL+encfQhWG2q1GqNS8pnwf2/iw5cL3mc63QfaWh8ZVingAfewLNYRnu3LZbcSrI+/Oj5mr4c8bSquouDRBm0zK6BdTuaXVv8oHI2wRMLNo3c5qjdlDhUI5lbUNxuNaND7NO0dIA0ti03T04GHDqrtrkn/B2VyvEhn4N2ksS8MacR8FWTDfadK/kXm78RquymaKyiRgOp5LPh7ggaI0ipw=}
