travis:
  secure:
    BINSTAR_TOKEN: hmhL7jN+Q3ETrEGnqCN5TiT2AMjcTYp28FKtIoxuo3ZFut7qo+Ck+g8porlt0XIXj137dzMlYi9SIaZz1yb9xPLhwust0dLnd8UvbQui6aoj1kD/uWnae+VpW00DO2XChm8HULCM4HxQ6R1SzOzKnmHt0A3VRG3snTw5hbIMhG9Uqobfd16HWo2NkC85wTfBTq/OgnRD2b9whZjvhRe5DJYApi6clzTf7RvuBMMe3fNn4kPzLq9/JBw1s1cn95XdvJZObnezcDEvIm6tFVoSHPeFSEf4SrC6bMbM1dU0enK9cqk9zw4Xg3ccz0YG/l0MISR8+51xWsIkTregBT5F+P9nR85DY4OvuKPwJzBLlwbVPV3JyJxj6pVHztJnZArGkhbaKcbT9QooC3wD8I3SGadPtEXGxZ8gSPcnIjudA8flWDBKmRhqOAtMsR+C+AfNVKdU6P7cNa+hKpdbwFOeRz54sWIfR5XVf0HbBYEaKaM706snQawcLhTeOfawLiSBVSjUJakk4xOrv0/s5O9QqypZQDcLoF8YNZ1unRWem1yqhzyNAnuuQHtinWXk/ChLjNH21+PWKARJV/5B06HTIcyTZGNi3I7NcIWOa438j6zwf0J/8PPE/m5oX2M4rswPLRiVYgI5tAE4qrwM1i2d06ac5tvP5uwSCsASeoJRWWY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
